### ISSUE TITLE
Building: how to deal with fwconsole chown timeout

### ISSUE THREAD

**Issue by crazyquark** [epandi/asterisk15-freepbx14#2]
Hi,

I've  tried building this image several times but I am blocked by the astersisk install step where it times out "Chowning directories....".
Any way to remove the timeout? How did you deal with it?

**Comment by epandi** [comment]
I've stoppen all my other docker containers and only startend the build proces of this Dockerfile. Rook around 2.5 hours to build in a rpi 3b+. When I had my other containers ruinnig I ran put of memory compilong asterisk.
