### ISSUE TITLE
Exposed ports 5060 and 5160 should be UDP not TCP.

### ISSUE THREAD

**Issue by crazyquark** [epandi/asterisk15-freepbx14#3]
Ports 5060 and 5160 need to be UDP for SIP.

**Comment by epandi** [comment]
I'll try to rebuild in the comming days with this change. Also want to reduce the image size by using only 1 run command in the Dockerfile.

**Comment by teixemf** [comment]
SIP is normally used over UDP but can also be used over TCP. IMO both should be setup.
